project:
  type: website
  output-dir: docs

website:
  title: "Learning Secure Web Gateway - Use-Cases"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: secure-web-gateway-foo.qmd
        text: Secure Web Gateway Foo

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
